export let movies = [
    {
        id: 1,
        title: 'the old guard',
        director: 'Gina Prince-Bythewood',
        runtime: '2hr 30min',
        votes: 30009,
        available: true,
        category: 'action',
        coverImage: 'the_old_guard.jpg',
        stars: ['Charlize Theron', 'KiKi Layne', 'Matthias Schoenaerts', 'Marwan Kenzari'],
        description: 'A covert team of immortal mercenaries are suddenly exposed and must now fight to keep their identity a secret just as an unexpected new member is discovered.',
    },
    {
        id: 2,
        title: 'greyhound',
        director: 'Aaron Schneider',
        runtime: '1hr 31min',
        votes: 33298,
        available: true,
        category: 'action',
        coverImage: 'greyhound.jpg',
        stars: ['Tom Hanks', 'Elisabeth Shue', 'Stephen Graham', 'Matt Helm'],
        description: 'Early in World War II, an inexperienced U.S. Navy captain must lead an Allied convoy being stalked by Nazi U-boat wolfpacks.',
    },
    {
        id: 3,
        title: 'hamilton',
        director: 'Thomas Kail',
        runtime: '1hr 31min',
        votes: 29150,
        available: true,
        category: 'comedy',
        coverImage: 'hamilton.jpg',
        stars: ['Lin-Manuel Miranda', 'Phillipa Soo', 'Leslie Odom Jr.', 'Renée Elise Goldsberry'],
        description: `The real life of one of America's foremost founding fathers and first Secretary of the Treasury, Alexander Hamilton. Captured live on Broadway from the Richard Rodgers Theater with the original Broadway cast.`,
    },
    {
        id: 4,
        title: 'the new mutants',
        director: 'Josh Boone',
        runtime: '1hr 38min',
        votes: 52993,
        available: true,
        category: 'comedy',
        coverImage: 'the-new-mutants.jpg',
        stars: ['Maisie Williams', 'Anya Taylor-Joy', 'Charlie Heaton', 'Blu Hunt'],
        description: `Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.`,
    },
    {
        id: 5,
        title: 'tenet',
        director: 'Christopher Nolan',
        runtime: '1hr 50min',
        votes: 2935,
        available: true,
        category: 'action',
        coverImage: 'tenet.jpg',
        stars: ['John David Washington', 'Robert Pattinson', 'Elizabeth Debicki', 'Aaron Taylor-Johnson'],
        description: `Armed with only one word -- Tenet -- and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.`,
    },
    {
        id: 6,
        title: 'the silencing',
        director: 'Robin Pront',
        runtime: '1hr 33min',
        votes: 2000,
        available: true,
        category: 'action',
        coverImage: 'the-silencing.jpg',
        stars: ['Nikolaj Coster-Waldau', 'Caleb Ellsworth-Clark', 'Josh Cruddas'],
        description: `A reformed hunter living in isolation on a wildlife sanctuary becomes involved in a deadly game of cat and mouse when he and the local Sheriff set out to track a vicious killer who may have kidnapped his daughter years ago.`,
    },
    {
        id: 7,
        title: 'the outpost',
        director: 'Rod Lurie',
        runtime: '2hr 3min',
        votes: 6188,
        available: true,
        category: 'action',
        coverImage: 'the-outpost.jpg',
        stars: ['Caleb Landry Jones', 'Orlando Bloom', 'Scott Eastwood'],
        description: `A small team of U.S. soldiers battle against hundreds of Taliban fighters in Afghanistan.`,
    },
    {
        id: 8,
        title: 'peninsula',
        director: 'Sang-ho Yeon',
        runtime: '1hr 44min',
        votes: 1004,
        available: true,
        category: 'action',
        coverImage: 'peninsula.jpg',
        stars: ['Dong-Won Gang', 'Jung-hyun Lee', 'John D. Michaels', 'Re Lee'],
        description: `Sequel to the 2016 South Korean zombie film Train to Busan`,
    },
    {
        id: 9,
        title: 'desperados',
        director: 'LP',
        runtime: '1hr 45min',
        votes: 5636,
        available: true,
        category: 'comedy',
        coverImage: 'desperados.jpg',
        stars: ['Nasim Pedrad', 'Anna Camp', 'Lamorne Morris', 'Sarah Burns'],
        description: `A panicked young woman, with her reluctant friends in tow, rushes to Mexico to try and delete a ranting email she sent to her new boyfriend.`,
    },
];